In [27]:
importnumpyasnp
importscipy.linalg
a=np.array([[1,2,3,4,5],[4,5,6,8,9]])
printa.ndim
printa.size
printa.shape
printa.shape[a.ndim-1]
printnp.array([[1.,2.,3.],[4.,5.,6.]])
b=np.array([[4,5],[6,8]])
c=np.array([6,7,8,9,10])
d=np.array([9,10])
printnp.vstack([np.hstack([a,b]),np.hstack([c,d])])
printa[-1]
printa[1,4]
printa[1] 
printa[0:5] 
printa[-5:]
printa[0:3][:,4:9]
printa[ix_([1,3,4],[0,2])]
printa[ 2:21:2,:]
printa[ ::2,:]
printa[ ::-1,:]
printa[r_[:len(a),0]]
#a.transpose()
#a.conj().transpose() 
#a.dot(b)
#a * b
#a/b
#a**3
#(a>0.5)
#nonzero(a>0.5)
#a[:,nonzero(v>0.5)[0]]
#a[:,v.T>0.5]
#a[a<0.5]=0
#a * (a>0.5)
#a[:] = 3
#y = x.copy()
#y = x[1,:].copy()
#y = x.flatten()
#arange(1.,11.)
#arange(10.)
#arange(1.,11.)[:, newaxis]
#zeros((3,4))
#zeros((3,4,5))
#ones((3,4))
#eye(3)
#diag(a)
#diag(a,0)
#random.rand(3,4)
#linspace(1,3,4)
#mgrid[0:9.,0:6.] 
#ogrid[0:9.,0:6.]
#meshgrid([1,2,4],[2,4,5])
#ix_([1,2,4],[2,4,5])
#tile(a, (m, n))
#concatenate((a,b),1) 
#vstack((a,b))
#a.max()
#a.max(0)
#a.max(1)
#maximum(a, b)
#np.linalg.norm(v)
#logical_and(a,b)
#logical_or(a,b)
#a & b
#a | b
#linalg.inv(a)
#linalg.pinv(a)
#linalg.matrix_rank(a)
#linalg.solve(a,b) if a issquare; linalg.lstsq(a,b) otherwise
#Solvea.Tx.T=b.Tinstead
#U, S, Vh = linalg.svd(a), V =Vh.T
#linalg.cholesky(a).T
#D,V = linalg.eig(a)
#V,D = np.linalg.eig(a,b)

#Q,R = scipy.linalg.qr(a)
#L,U = scipy.linalg.lu(a)
#scipy.sparse.linalg.cg
#fft(a)
#ifft(a)
#sort(a)
#I = argsort(a[:,i]), b=a[I,:]
#linalg.lstsq(X,y)
#scipy.signal.resample(x,len(x)/q)
#unique(a)
#a.squeeze()


2
10
(2, 5)
5
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 1  2  3  4  5  4  5]
 [ 4  5  6  8  9  6  8]
 [ 6  7  8  9 10  9 10]]
[4 5 6 8 9]
9


In [129]:
import numpy as np
import scipy.linalg as linalg
import scipy.sparse.linalg
import scipy.signal
a = np.array([[1,2,3,4,5,6],[4,5,6,8,9,10]])
print a.ndim
print np.size(a)
print np.shape(a)
print a.shape[a.ndim-1]
print np.array([[1.,2.,3.],[4.,5.,6.]])

b = np.array([[4,5],[6,8]])
c = np.array([6,7,8,9,10,11])
d = np.array([9,10])
print np.vstack([np.hstack([a,b]),np.hstack([c,d])])
print a[-1]
print a[1,4]
print a[1]
print a[0:5]
print a[-5:]
print a[0:3][:,4:9]
print a
a = np.ones((22,3))
print a[np.ix_([1,3,4],[0,2])]
print a[2:21:2,:]
print a[::2,:]
print a[::-1,:]
print a[np.r_[:len(a),0]]
print a.transpose()
print a.conj().transpose()
a = np.ones((3,3))
b = np.ones((3,3))
print a.dot(b)
print a*b
print a/b
print a**3
print (a>0.5)
print np.nonzero(a>0.5)
v=np.array([0.1,1])
print a[:,np.nonzero(v>0.5)[0]]
print a[:,v.T>0.5]
a[a<0.5]=0
print a
print a*(a>0.5)
a[:]=3
print a
x = np.array([[1,2],[3,4]])
y=x.copy()
print y
y=x[1,:].copy()
print y
y=x.flatten()
print y
print np.arange(1.,11.)
print np.arange(10.)
print np.arange(1.,11.)[:,np.newaxis]
print np.zeros((3,4))
print np.zeros((3,4,5))
print np.ones((3,4))
print np.eye(3)
print np.diag(a)
print np.diag(a,0)
print np.random.rand(3,4)
print np.linspace(1,3,4)
print np.mgrid[0:9.,0:6.]
print np.ogrid[0:9.,0:6.]
print np.meshgrid([1,2,4],[2,4,5])
print np.ix_([1,2,4],[2,4,5])
m =1
n=2
print np.tile(a,(m,n))
print np.concatenate((a,b),1)
print np.concatenate((a,b))
print a.max()
print a.max(0)
print a.max(1)
print np.maximum(a,b)
print np.sqrt(np.dot(v,v))
print np.logical_and(a,b)
print np.logical_or(a,b)
print (a==1)&(b==1)
print (a==1)|(b==1)
a = np.array([[1,2],[3,4]])
print linalg.inv(a)
print linalg.pinv(a)
print np.linalg.matrix_rank((np.eye(4)))
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
print linalg.lstsq(A,y)
U,S,Vh=linalg.svd(a)
print U,S,Vh
V=Vh.T
print V
a = np.array([[ 1.+0.j,  0.-2.j],
       [ 0.+2.j,  5.+0.j]])
print linalg.cholesky(a).T
D,V=linalg.eig(a)
print D,V
V,D=np.linalg.eig(np.diag((1, 2, 3)))
Q,R=linalg.qr(a)
print V,D,Q,R
A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P,L,U=linalg.lu(A)
print P,L,U
print scipy.sparse.linalg.cg
print np.fft.fft(a)
print np.fft.ifft(a)
print np.sort(a)
a = np.array([[0, 3], [2, 2]])
I=np.argsort(a[:,1])
b=a[I,:]
print b
print scipy.signal.resample(x,len(x)/2)
print np.unique(a)
print a.squeeze()

2
12
(2, 6)
6
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[ 1  2  3  4  5  6  4  5]
 [ 4  5  6  8  9 10  6  8]
 [ 6  7  8  9 10 11  9 10]]
[ 4  5  6  8  9 10]
9
[ 4  5  6  8  9 10]
[[ 1  2  3  4  5  6]
 [ 4  5  6  8  9 10]]
[[ 1  2  3  4  5  6]
 [ 4  5  6  8  9 10]]
[[ 5  6]
 [ 9 10]]
[[ 1  2  3  4  5  6]
 [ 4  5  6  8  9 10]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[

/Users/user/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:41: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 2


In [53]:
a[a<0.5]=0

In [54]:
a = 1

In [55]:
a

1

In [140]:
import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,2,7,14])
plt.axis([0, 6, 0, 20])
plt.savefig("3.png")

In [145]:
import matplotlib.pyplot as plt
import numpy as np
x = np.arange(-2*np.pi, 2*np.pi, 0.01)
y = np.sin(x)
fig = plt.figure(figsize=(4, 5))
ax = fig.add_subplot(111)
ax.plot(x, y,linewidth="3", alpha=0.3)
plt.savefig("4.png")
